language: node_js
node_js:
  - iojs

before_script:
  - npm install

script:
  - npm run test
  - npm run build

deploy:
  provider: npm
  email: zhongjh1994@gmail.com
  api_key:
    secure: r0gciy3z5kBEjVZp8xBC++eljaRXOO4s8rn8FeqDnma28KXLvUj1RilQGtB0EjXaxaFcp49yM/SwGQVqRhbMGlcotzyz7ONcVZrMrlYj6tHJQ9JD3jjgsiJQBhtt3k+jeS4rf3DTGMR0EiizaIzy+p/ItF8h3LjMz4g765Y/p+bhA+QxfTLWc+NfURo/hF6T9y7e4S+FTHyG4uHhR58RtYdPi1AgfUYbIIpxlRhHWvzpL3yyxv/8cizZJAWBrCWyisQw84TNAjtoHTVXrbS4tPDF/76WIwD6iTR+iofDqCcVOSij/5EHvW609YgoRz7ohTUVQj1vpGyFe+SM0E2AJRuY+ejy+LLczWcdmhr0krcLj6oII2vr1i/YyMI5UDKnkpAS4wXpvWZpkkNamYZuR1uBV3RxMB954q6wIs6Ss237ZChZgiCaOSj4gHjqqZWPBzAcyBNse0ixrnUK6fHLI10jBk/W1IHag5cJMKwQpsLFhFVxB4akf/Vbct5A2X4paiT0Bto4kVzoek2aGP14wnw7BoPSYtyFgFFCsAYEWaTo8TvAPzJAaizoZwkETMezFYX5pFMKheqsbJDL2Zrn6OKxlF/5gUbN1VBR0nufg8OANMKEYIYNpUWB4VHCXXVOJ0RWJtC6/SznwhoQUg0HTtwuDOaiDtxjIomAtK7cOdo=
  on:
    tags: true


cache:
  directories:
  - node_modules
